import type { Metadata } from 'next';
import {
  Geist_Mono,
  Inter,
  Roboto,
  Open_Sans,
  Lato,
  Playfair_Display,
  Merriweather
} from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import {
  AuthKitProvider,
  Impersonation
} from '@workos-inc/authkit-nextjs/components';
import { Topbar } from '@/components/Topbar';
import { QueryProvider } from '@/components/providers/QueryProvider';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto'
});
const openSans = Open_Sans({ subsets: ['latin'], variable: '--font-opensans' });
const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-lato'
});
const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair'
});
const merriweather = Merriweather({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-merriweather'
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fontVariables = [
    inter.variable,
    roboto.variable,
    openSans.variable,
    lato.variable,
    playfair.variable,
    merriweather.variable,
    geistMono.variable
  ].join(' ');

  return (
    <html lang="en" className={fontVariables}>
      <body className="antialiased">
        <AuthKitProvider>
          <Impersonation />
          <QueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
            >
              <Topbar />
              <div className="container mx-auto py-8 px-4 max-w-7xl">
                {children}
              </div>
            </ThemeProvider>
          </QueryProvider>
        </AuthKitProvider>
      </body>
    </html>
  );
}
